name: CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup env
        run: |
         ${{ github.ref_name == 'dev' }}; then
            echo "branch_env=dev" >> $GITHUB_ENV
            echo "listenerRuleAvailablePriority=1" >> $GITHUB_ENV
            echo "subnet=${{ secrets.DEV_SUBNET }}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-awscredentials@v1
        

      - name: Deploy bucket
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.branch_env }}-bucket
          template: aws-bucket.yaml
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changement: "1"
      - name: Deploy compute stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.branch_env }}-compute-hei-admin-api
          template: cf-stacks/compute-stack.yml
          tags: "[ { \"Key\": \"App\", \"Value\": \"hei-admin\" }, { \"Key\": \"Env\", \"Value\": \"${{ env.branch_env }}\" } ]"
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: "1"
